services:
  cursos-api:
    image: cursosdev-api
    build:
      context: .
      dockerfile: CursosDev.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=CursosDevDb;Username=postgres;Password=password123
      - Jwt__Key=CursosDevSuperSecretKeyForJwtAuthenticationMustBeAtLeast32Characters!
      - Jwt__Issuer=CursosDev
      - Jwt__Audience=CursosDevUsers
      - Jwt__ExpirationMinutes=60
    depends_on:
      db:
        condition: service_healthy
      cursos-tests:
        condition: service_completed_successfully

  cursos-web:
    image: cursosdev-web
    build:
      context: ./CursosDev.Web
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - cursos-api

  cursos-tests:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    container_name: cursosdev_tests
    volumes:
      - .:/src
    working_dir: /src
    command: dotnet test CursosDev.Tests/CursosDev.Tests.csproj

  db:
    image: postgres:17-alpine
    container_name: cursosdev_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: CursosDevDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: